version: "3.3"

services:
  website:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    image: dotcom
    volumes:
      - .:/usr/src/app
      - /usr/src/node_modules
      - /usr/src/app/.next

