env:
  DOCKER_IMAGE: "bwilytsch/dotcom:0.0.1"  

name: Build & Deploy
on:
  push:
    branches: [ master ]

jobs:       
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login & Build & Push
        uses: actions/checkout@v2
        with:
          envs: DOCKER_IMAGE
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker build --tag $DOCKER_IMAGE .
            docker push $DOCKER_IMAGE    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.BWILYTSCH_SECRET }}
          passphrase: ${{ secrets.BWILYTSCH_SECRET_PASSPHRASE }}
          envs: DOCKER_IMAGE  
          port: 22
          script: |
            docker stop $(docker ps -a -q)
            docker pull $DOCKER_IMAGE
            docker run -dit -p 80:1234 $DOCKER_IMAGE   
    
