env:
  DOCKER_IMAGE: "bwilytsch/dotcom:0.0.1"  

name: Deployment Action
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.BWILYTSCH_SECRET }}
          passphrase: ${{ secrets.BWILYTSCH_SECRET_PASSPHRASE }}
          envs: DOCKER_IMAGE  
          port: 22
          script: |
            docker stop $(docker ps -a -q)
            docker pull $DOCKER_IMAGE
            docker run -dit -p 80:1234 $DOCKER_IMAGE
